apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: shipping-dev
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: "docker pull asia.gcr.io/trial-velostrata/hello-node:latest"
